# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
-   task: Bash@3
    inputs:
      targetType: 'inline'
      script: |
        echo $API_UID
        echo $API_ACCESS_TOKEN
        echo $API_CLIENT
        echo $PROJECT_ID
        echo $PROJECT_TOKEN
        echo $TEST_RUN_ID
    env:
        API_UID: $(API_UID)
        API_ACCESS_TOKEN: $(API_ACCESS_TOKEN)
        API_CLIENT: $(API_CLIENT)
        PROJECT_ID: $(PROJECT_ID)
        PROJECT_TOKEN: $(PROJECT_TOKEN)
        TEST_RUN_ID: $(TEST_RUN_ID)

-   task: ShellScript@2
    inputs:
        scriptPath: serenity.sh
        args: 'sync'

-   task: ShellScript@2
    inputs:
      scriptPath: serenity.sh
      args: 'update_features'
      
-   task: ShellScript@2
    inputs:
      scriptPath: serenity.sh
      args: 'run_tests local'